{{- if .Values.wordpress }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ .Values.wordpress.name }}
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Values.wordpress.namespace }}
spec:
  replicas: {{ .Values.wordpress.deployment.replica }}
  selector:
    matchLabels:
      name: {{ .Values.wordpress.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.wordpress.name }}
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.deployment.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: {{ .Values.wordpress.name }}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-ebs
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}
              key: MYSQL_ROOT_PASSWORD
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.mysql.name }}.{{ .Values.mysql.namespace }}
      volumes:
      - name: "wordpress-ebs"
        persistentVolumeClaim:
          claimName: {{ .Values.wordpress.name }}-pvc
{{- end }}

---
{{- if .Values.mysql }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ .Values.mysql.name }}
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  replicas: {{ .Values.mysql.deployment.replica }}
  selector:
    matchLabels:
      name: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.deployment.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: wordpress-mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-ebs
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}
              key: MYSQL_ROOT_PASSWORD
      volumes:
      - name: "mysql-ebs"
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.name }}

{{- end }}