apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.passowrd | b64enc}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.wordpress.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.passowrd | b64enc}}